mod max_common_prefix;
mod prefixes_div_by5;
mod last_stone_weight;
mod duplicate_zeros;
mod relative_sort_array;
mod distribute_candies;
mod count_characters;
mod remove_duplicates;
mod balanced_string_split;
mod min_time_to_visit_all_points;
pub mod unique_occurrences;
mod odd_cells;
mod defang_i_paddr;
mod gcd_of_strings;
pub mod merge;
mod tribonacci;